### ISSUE TITLE
Build error 2

### ISSUE THREAD

**Issue by Iskers** [ivanmejiarocha/micro-service#14]
I get this error when trying to build. Iv tried changing Openssl version and Cpprestsdk version in dependencies CMakeLists. Do you have a solution?

`make[2]: *** No rule to make target `../libs/cpprestsdk/build.release/Binaries/libcpprest.a', needed by `micro-service'.  Stop.
make[1]: *** [CMakeFiles/micro-service.dir/all] Error 2
make: *** [all] Error 2
`
<img width="1435" alt="skjermbilde 2019-01-31 kl 00 46 05" src="https://user-images.githubusercontent.com/22838996/52020468-a8d8a780-24f1-11e9-81a5-ee03cd61a531.png">

<img width="1183" alt="skjermbilde 2019-01-31 kl 00 47 06" src="https://user-images.githubusercontent.com/22838996/52020493-bf7efe80-24f1-11e9-9f7c-71d0282a9afc.png">

**Comment by ivanmejiarocha** [comment]
Hi Iskers,
 Did you ran first the build_dependencies.sh?

Thanks!
Ivan.

**Comment by Iskers** [comment]
Yes, i ran it before building. I'v tried running it with both with `RESTSDK_VERSION="v2.10.6"` and `RESTSDK_VERSION="v2.10.6"`.

**Comment by ivanmejiarocha** [comment]
Hi Iskers,
    It looks like you have not build the C++ REST SDK, please leave the build_dependencies as is, and please verify the path:

    ../libs/cpprestsdk/build.release/Binaries/

it should contain the file `libcpprest.a`, e.i.:

    $ ls ../libs/cpprestsdk/build.release/Binaries

you should see this output:

    $ ls ../libs/cpprestsdk/build.release/Binaries
    libcpprest.a

if that file is not there then that's your problem, the C++ REST SDK is not build.

Thanks,
Ivan.

**Comment by vineetdodd** [comment]
The file is definetly there in my case, I am still getting the same error. It fails on step 5, and says

"""
make[2]: *** No rule to make target `/usr/local/Cellar/openssl/1.0.2p/lib/libssl.1.0.0.dylib', needed by `micro-service'.  Stop.
make[1]: *** [CMakeFiles/micro-service.dir/all] Error 2
make: *** [all] Error 2
"""

Any ideas? Couldn't find anything in the comments above. Thanks!

**Comment by emiles002** [comment]
Same error, here, after running 'make -j 8"

running macOS 10.14.3

**Comment by ivanmejiarocha** [comment]
you have to install OpenSSL, If you ar on macOS type:
```
$ brew install cmake git openssl boost zlib
```

**Comment by pmeade** [comment]
That workaround fixed it for me. Thank you so much

**Comment by ivanmejiarocha** [comment]
Thanks, I'm glad it helped.

**Comment by DLinIoTedge** [comment]
Hello Ivan,  good morning.  

 Machine: Ubuntu 18.04 X86 AMD

libcpprest.a is created by using ./build_dependencies.sh

  cmake is done in micro-service/build$  
  during make -j 8  the following error msg coming 
 undefined reference to `deflate'

Could you kindly advice
Thanks a lot in advance
jk
