### ISSUE TITLE
Parsing Json

### ISSUE THREAD

**Issue by documentdriver** [ivanmejiarocha/micro-service#15]
Hello Ivan,
Thank you for sharing this great work.
I'm trying to parse a simple Json request object from a Post request.

{"page":1, "pageSize":10}

None of the examples I found work properly. For example "class web::json::value’ has no member named ‘cbegin’".

I could see how you made a json object from scratch and it's very easy.
Do you have some easy (or not so easy) way to do the get the json object from a request?
Thanks in advance,
Diego

**Comment by coldweek** [comment]
Hello,
io am facing the same problem...did you find the solution? If yes, can you share it?
Thanks in advance
Adrian..
